version: "3"
services:
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shortener
    networks:
      - link-shortener-network
    volumes:
      - short-linkiner-db:/var/docker_volumes/short_linkiner/

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "80:80"
    networks:
      - link-shortener-network

volumes:
  short-linkiner-db:

networks:
  link-shortener-network:
    driver: bridge